### ISSUE TITLE
NetworkX error when using prune_tree in Ms Pacman demo

### ISSUE THREAD

**Issue by justindujardin** [FragileTech/fragile#6]
Hi, I noticed that when running the ms pacman demo for more iterations than the default, the movie playback at the end tends to crash with this error:

```
Traceback (most recent call last):
  File "fragile/ms_pacman.py", line 45, in <module>
    path = swarm.tree.get_branch(best_id, from_hash=True)
  File "fragile/fragile/core/tree.py", line 122, in get_branch
    nodes = nx.shortest_path(self.data, root, leaf_name)
  File "fragile/.env/lib/python3.6/site-packages/networkx/algorithms/shortest_paths/generic.py", line 170, in shortest_path
    paths = nx.bidirectional_shortest_path(G, source, target)
  File "fragile/.env/lib/python3.6/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 226, in bidirectional_shortest_path
    results = _bidirectional_pred_succ(G, source, target)
  File "fragile/.env/lib/python3.6/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 294, in _bidirectional_pred_succ
    raise nx.NetworkXNoPath("No path between %s and %s." % (source, target))
networkx.exception.NetworkXNoPath: No path between 0 and 64036.
```

I suspect this is because prune_tree has removed the referenced nodes. I confirmed the crash is related to `prune_tree` indirectly by re-running the experiment multiple times with the flag toggled, and it only crashes when True.

**Comment by Guillemdb** [comment]
Hmm... I thought I had fixed it. you are right, some referenced node gets removed when it shouldn't. 

Does it always happen? It is some kind of edge case that I am not finding right now. 

 I was planning to write the tests for the tree next week, but If you give me a code snippet to reproduce the error I will fix it ASAP.

**Comment by justindujardin** [comment]
If you point me at the right spot to set a breakpoint in the tree, I can check on the particular nodes. The example python notebook is where I saw the error originally, but I extracted the code into a standalone .py file, and it reproduces on almost every run: 
```python
import time

from fragile.atari.env import AtariEnv
from fragile.core.dt_sampler import GaussianDt
from fragile.core.models import DiscreteUniform
from fragile.core.swarm import Swarm
from fragile.core.tree import HistoryTree
from plangym import AtariEnvironment, ParallelEnvironment

game_name = "MsPacman-ram-v0"
env = ParallelEnvironment(
    env_class=AtariEnvironment, name=game_name, clone_seeds=True, autoreset=True, blocking=False,
)


env_callable = lambda: AtariEnv(env=env)


dt = GaussianDt(min_dt=3, max_dt=1000, loc_dt=4, scale_dt=2)
model_callable = lambda env: DiscreteUniform(env=env, critic=dt)


prune_tree = True
n_walkers = 64  # A bigger number will increase the quality of the trajectories sampled.
max_iters = 1000  # Increase to sample longer games.
reward_scale = 2  # Rewards are more important than diversity.
distance_scale = 1
minimize = False  # We want to get the maximum score possible.


swarm = Swarm(
    model=model_callable,
    env=env_callable,
    tree=HistoryTree,
    n_walkers=n_walkers,
    max_iters=max_iters,
    prune_tree=prune_tree,
    reward_scale=reward_scale,
    distance_scale=distance_scale,
    minimize=minimize,
)
_ = swarm.run_swarm(print_every=50)
best_ix = swarm.walkers.states.cum_rewards.argmax()
best_id = swarm.walkers.states.id_walkers[best_ix]
path = swarm.tree.get_branch(best_id, from_hash=True)


for s, a in zip(path[0][1:], path[1]):
    env.step(state=s, action=a)
    env.render()
    time.sleep(0.05)

print("Done!")

```

**Comment by Guillemdb** [comment]
I think I found the bug. I am working on it.

**Comment by Guillemdb** [comment]
I was removing the root node. I am documenting the class before uploading the fix.
![buggy_graph](https://user-images.githubusercontent.com/7149899/76150097-e6214880-60a6-11ea-9675-b83f6a42aa49.png)

**Comment by Guillemdb** [comment]
I uploaded the fix. If you find again the same error please reopen the Issue.

**Comment by Guillemdb** [comment]
Looks like it's not solved. I am working on it.
